---
- name: create config dir
  file:
    path: "{{ prometheus_config_dir }}"
    state: directory

- name: create endpoints config dir
  file:
    path: "{{ prometheus_cfg_endpoint_dir }}"
    state: directory

- name: install config file
  template:
    src: templates/slurmjobs-prometheus-exporter.yml.j2
    dest: "{{ prometheus_cfg_endpoint_dir }}/slurmjobs-prometheus-exporter.yml"
    owner: root
    group: root
    mode: 0644

- name: install systemd unit file
  template:
    src: templates/slurmjobs-prometheus-exporter.service.j2
    dest: "/etc/systemd/system/{{ slurmjobs_prometheus_exporter_svc_name }}"
    owner: root
    group: root
    mode: 0644

- name: configure service
  systemd:
    name: "{{ slurmjobs_prometheus_exporter_svc_name }}"
    state: "{{ slurmjobs_prometheus_exporter_state }}"
    enabled: "{{ slurmjobs_prometheus_exporter_enabled }}"
    daemon_reload: yes
  notify: restart slurmjobs-prometheus-exporter
